### ISSUE TITLE
presto-connector module with "No factory for connector odps"

### ISSUE THREAD

**Issue by wowtous** [aliyun/aliyun-maxcompute-data-collectors#110]
ERROR	main	com.facebook.presto.server.PrestoServer	No factory for connector odps
java.lang.IllegalArgumentException: No factory for connector odps
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:216)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:194)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:96)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:74)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:132)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:74)

**Comment by wowtous** [comment]
done

**Comment by wowtous** [comment]
done
