### ISSUE TITLE
trino-connector odps表查询报错

### ISSUE THREAD

**Issue by malin01** [aliyun/aliyun-maxcompute-data-collectors#135]
Query 20230301_042651_00012_j7ivw is FAILED
2023-03-01T12:27:27.607+0800    DEBUG   query-execution-23      io.trino.execution.QueryStateMachine    Query 20230301_042651_00012_j7ivw failed
java.lang.NullPointerException
        at com.aliyun.odps.cupid.trino.OdpsRecordCursor.getValueInternal(OdpsRecordCursor.java:65)
        at com.aliyun.odps.cupid.trino.OdpsRecordCursor.isNull(OdpsRecordCursor.java:170)
        at io.trino.spi.connector.RecordPageSource.getNextPage(RecordPageSource.java:96)
        at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:311)
        at io.trino.operator.Driver.processInternal(Driver.java:388)
        at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
        at io.trino.operator.Driver.tryWithLock(Driver.java:685)
        at io.trino.operator.Driver.processFor(Driver.java:285)
        at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1078)
        at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
        at io.trino.$gen.Trino_364____20230301_040204_2.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by jackchongs** [comment]
遇到相同的问题。 使用 Presto版本反而可以
