### ISSUE TITLE
Sqoop could not parse record when exporting data from MaxCompute to PostgreSQL

### ISSUE THREAD

**Issue by giaosudau** [aliyun/aliyun-maxcompute-data-collectors#9]
Hi Ali,
I am using sqoop to export data from Maxcompute to Postgres.
```
./odps-sqoop/bin/sqoop export --connect jdbc:postgresql://localhost:5432/replication_db --table dim_wmp_cabinet \
    --username replication_user --password replication_pass \
    --odps-table dim_wmp_cabinet --odps-project xxx --odps-accessid xxx \
    --odps-tunnel-endpoint http://xxxx \
    --odps-partition-spec ds=20170916 \
    --odps-accesskey xxxx --odps-endpoint http://sxxx/api
```
I am looking into this code
OdpsExportMapper.java
```
try {
      odpsImpl.parse(val);
      context.write(odpsImpl, NullWritable.get());
```

I am success to add tunnel endpoint into source code but couldn't get through this one.

Please help fix this issue.

```
17/09/18 18:16:46 INFO mapreduce.Job: The url to track the job: http://localhost:8080/
17/09/18 18:16:46 INFO mapreduce.Job: Running job: job_local873411290_0001
17/09/18 18:16:46 INFO mapred.LocalJobRunner: OutputCommitter set in config null
17/09/18 18:16:46 INFO mapred.LocalJobRunner: OutputCommitter is org.apache.sqoop.mapreduce.NullOutputCommitter
17/09/18 18:16:46 INFO mapred.LocalJobRunner: Waiting for map tasks
17/09/18 18:16:46 INFO mapred.LocalJobRunner: Starting task: attempt_local873411290_0001_m_000000_0
17/09/18 18:16:46 INFO util.ProcfsBasedProcessTree: ProcfsBasedProcessTree currently is supported only on Linux.
17/09/18 18:16:46 INFO mapred.Task:  Using ResourceCalculatorProcessTree : null
17/09/18 18:16:46 INFO mapred.MapTask: Processing split: org.apache.sqoop.mapreduce.odps.OdpsExportInputFormat$OdpsExportInputSplit@6a6d595f
17/09/18 18:16:46 ERROR odps.OdpsExportMapper: Exception raised during data export
17/09/18 18:16:46 ERROR odps.OdpsExportMapper: Exception:
java.lang.RuntimeException: Can't parse input data: '3'
	at dim_wmp_cabinet.__loadFromFields(dim_wmp_cabinet.java:2090)
	at dim_wmp_cabinet.parse(dim_wmp_cabinet.java:1533)
	at org.apache.sqoop.mapreduce.odps.OdpsExportMapper.map(OdpsExportMapper.java:77)
	at org.apache.sqoop.mapreduce.odps.OdpsExportMapper.map(OdpsExportMapper.java:35)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146)
	at org.apache.sqoop.mapreduce.AutoProgressMapper.run(AutoProgressMapper.java:64)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:243)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at dim_wmp_cabinet.__loadFromFields(dim_wmp_cabinet.java:2010)
	... 13 more
17/09/18 18:16:46 ERROR odps.OdpsExportMapper: On input: com.aliyun.odps.data.ArrayRecord@4c665e0d
17/09/18 18:16:46 ERROR odps.OdpsExportMapper: At position 0
17/09/18 18:16:46 ERROR odps.OdpsExportMapper:
```

**Comment by oyz** [comment]
can you provide the schemas of table 'dim_wmp_cabinet' both in postgresql and MaxCompute respectively and give some example data please ?

**Comment by giaosudau** [comment]
MaxCompute
```
odps@ xxx>desc dim_wmp_cabinet;

+------------------------------------------------------------------------------------+
| TableComment:                                                                      |
+------------------------------------------------------------------------------------+
+------------------------------------------------------------------------------------+
| InternalTable: YES      | Size: 2025040                                            |
+------------------------------------------------------------------------------------+
| Native Columns:                                                                    |
+------------------------------------------------------------------------------------+
| Field           | Type       | Label | Comment                                     |
+------------------------------------------------------------------------------------+
| cabinet_id      | bigint     |       |                                             |
| gmt_create      | string     |       |                                             |
| gmt_modified    | string     |       |                                             |
| cabinet_code    | string     |       |                                             |
| warehouse_code  | string     |       |                                             |
| warehouse_name  | string     |       |                                             |
| warehouse_area_id | bigint     |       |                                             |
| warehouse_area_code | string     |       |                                             |
| roadway_id      | bigint     |       |                                             |
| roadway_code    | string     |       |                                             |
| status          | bigint     |       |                                             |
| length          | bigint     |       |                                             |
| width           | bigint     |       |                                             |
| height          | bigint     |       |                                             |
| max_capacity    | bigint     |       |                                             |
| max_weight      | bigint     |       |                                             |
| max_level       | bigint     |       |                                             |
| warehouse_area_type | bigint     |       |                                             |
| item_character  | bigint     |       |                                             |
| pack_mode       | bigint     |       |                                             |
| store_option    | bigint     |       |                                             |
| is_inferior     | bigint     |       |                                             |
| cabinet_type    | bigint     |       |                                             |
| left_right      | bigint     |       |                                             |
| sales_volume    | bigint     |       |                                             |
| storage_way     | bigint     |       |                                             |
| volume_rate     | bigint     |       |                                             |
| display_assort  | bigint     |       |                                             |
| max_kind_num    | bigint     |       |                                             |
| max_num         | bigint     |       |                                             |
| category        | bigint     |       |                                             |
| size_type       | bigint     |       |                                             |
| is_test         | bigint     |       |                                             |
| stock_type      | bigint     |       |                                             |
| pick_priority   | bigint     |       |                                             |
+------------------------------------------------------------------------------------+
| Partition Columns:                                                                 |
+------------------------------------------------------------------------------------+
| ds              | string     |                                                     |
+------------------------------------------------------------------------------------+

OK
```

PostgreSQL.

```
CREATE TABLE IF NOT EXISTS dim_wmp_cabinet (
  cabinet_id          BIGINT,
  gmt_create          TEXT,
  gmt_modified        TEXT,
  cabinet_code        TEXT,
  warehouse_code      TEXT,
  warehouse_name      TEXT,
  warehouse_area_id   BIGINT,
  warehouse_area_code TEXT,
  roadway_id          BIGINT,
  roadway_code        TEXT,
  status              BIGINT,
  length              BIGINT,
  width               BIGINT,
  height              BIGINT,
  max_capacity        BIGINT,
  max_weight          BIGINT,
  max_level           BIGINT,
  warehouse_area_type BIGINT,
  item_character      BIGINT,
  pack_mode           BIGINT,
  store_option        BIGINT,
  is_inferior         BIGINT,
  cabinet_type        BIGINT,
  left_right          BIGINT,
  sales_volume        BIGINT,
  storage_way         BIGINT,
  volume_rate         BIGINT,
  display_assort      BIGINT,
  max_kind_num        BIGINT,
  max_num             BIGINT,
  category            BIGINT,
  size_type           BIGINT,
  is_test             BIGINT,
  stock_type          BIGINT,
  pick_priority       BIGINT,
  ds                  TEXT
)
```
Sample data
```
| cabinet_id | gmt_create | gmt_modified | cabinet_code | warehouse_code | warehouse_name | warehouse_area_id | warehouse_area_code | roadway_id | roadway_code | status     | length     | width      | height     | max_capacity | max_weight | max_level  | warehouse_area_type | item_character | pack_mode  | store_option | is_inferior | cabinet_type | left_right | sales_volume | storage_way | volume_rate | display_assort | max_kind_num | max_num    | category   | size_type  | is_test    | stock_type | pick_priority | ds |
+------------+------------+--------------+--------------+----------------+----------------+-------------------+---------------------+------------+--------------+------------+------------+------------+------------+--------------+------------+------------+---------------------+----------------+------------+--------------+-------------+--------------+------------+--------------+-------------+-------------+----------------+--------------+------------+------------+------------+------------+------------+---------------+----+
| 8100083    | 2017-01-02 17:53:59 | 2017-01-02 17:53:59 | OOO-XXX-JUU   | OMS-CPN-WH2 | OMS-CPN-WH2 | 5036              | OOO-XXX-CPZCQ         | 13239      | OOO-XXX-CPZCQ | 1          | 1000       | 1000       | 1000       | 8100000000   | 8100000000 | 10000000   | 3                   | 4              | 3          | NULL         | -1          | NULL         | NULL       | 3            | NULL        | NULL        | NULL           | 999999       | 999999     | NULL       | NULL       | 1          | 6          | 9999999       | 20170913 |
| 8100084    | 2017-01-02 17:53:59 | 2017-01-02 17:53:59 | OOO-XXX-ZCQ   | OMS-CPN-WH2 | OMS-CPN-WH2 | 5037              | OOO-XXX-ZCQ           | 13240      | OOO-XXX-ZCQ  | 1          | 1000       | 1000       | 1000       | 8100000000   | 8100000000 | 10000000   | 3                   | 4              | 3          | NULL         | 1           | NULL         | NULL       | 3            | NULL        | NULL        | NULL           | 999999       | 999999     | NULL       | NULL       | 1          | 6          | 9999999       | 20170913 |
| 8100085    | 2017-01-02 17:53:59 | 2017-01-02 17:53:59 | OOO-GW-SHSH   | OMS-CPN-WH2 | OMS-CPN-WH2 | 5038              | OOO-GW-ZCQ            | 13241      | OOO-GW-ZCQ    | 1          | 1000       | 1000       | 1000       | 8100000000   | 8100000000 | 10000000   | 3                   | 4              | 3          | NULL         | 1           | NULL         | NULL       | 3            | NULL        | NULL        | NULL           | 999999       | 999999     | NULL       | NULL       | 1          | 6          | 9999999       | 20170913 |
| 8100086    | 2017-01-02 17:53:59 | 2017-01-02 17:53:59 | OOO-HCCCQ     | OMS-CPN-WH2 | OMS-CPN-WH2 | 5039              | OOO-HCCCQ             | 13242      | OOO-HCCCQ     | 1          | 1000       | 1000       | 1000       | 8100000000   | 8100000000 | 10000000   | 1                   | 4              | 3          | NULL         | 1           | NULL         | NULL       | 3            | NULL        | NULL        | NULL           | 999999       | 999999     | NULL       | NULL       | 1          | 1          | 9999999       | 20170913 |
| 8100087    | 2017-01-02 17:53:59 | 2017-01-02 17:53:59 | OOO-JGXJ-KLLJ | OMS-CPN-WH2 | OMS-CPN-WH2 | 5040              | OOO-XXX-CPZCQ         | 13243      | OOO-JGXJ-CPZCQ | 1          | 1000       | 1000       | 1000       | 8100000000   | 8100000000 | 10000000   | 3                   | 4              | 3          | NULL         | -1          | NULL         | NULL       | 3            | NULL        | NULL        | NULL           | 999999       | 999999     | NULL       | NULL       | 1          | 6          | 9999999       | 20170913 |
| 8100088    | 2017-01-02 17:53:59 | 2017-01-02 17:53:59 | OOO-DDD-BCBD  | OMS-CPN-WH2 | OMS-CPN-WH2 | 5041              | OOO-XXX-ZCQ           | 13244      | OOO-JGXJ-ZCQ  | 1          | 1000       | 1000       | 1000       | 8100000000   | 8100000000 | 10000000   | 3                   | 4              | 3          | NULL         | 1           | NULL         | NULL       | 3            | NULL        | NULL        | NULL           | 999999       | 999999     | NULL       | NULL       | 1          | 6          | 9999999       | 20170913 |
| 8100089    | 2017-01-02 17:53:59 | 2017-01-02 17:53:59 | OOO-SH-CPZCQ  | OMS-CPN-WH2 | OMS-CPN-WH2 | 5042              | OOO-SH-CPZCQ          | 13245      | OOO-SH-CPZCQ  | 1          | 1000       | 1000       | 1000       | 8100000000   | 8100000000 | 10000000   | 3                   | 4              | 3          | NULL         | -1          | NULL         | NULL       | 3            | NULL        | NULL        | NULL           | 999999       | 999999     | NULL       | NULL       | 1          | 6          | 9999999       | 20170913 |
| 8100090    | 2017-01-02 17:53:59 | 2017-01-02 17:53:59 | OOO-SH-JDJD   | OMS-CPN-WH2 | OMS-CPN-WH2 | 5043              | OOO-SH-ZCQ            | 13246      | OOO-SH-ZCQ    | 1          | 1000       | 1000       | 1000       | 8100000000   | 8100000000 | 10000000   | 3                   | 4              | 3          | NULL         | 1           | NULL         | NULL       | 3            | NULL        | NULL        | NULL           | 999999       | 999999     | NULL       | NULL       | 1          | 6          | 9999999       | 20170913 |
| 8100091    | 2017-01-02 17:53:59 | 2017-01-02 17:53:59 | OOO-TG-IHJK   | OMS-CPN-WH2 | OMS-CPN-WH2 | 5044              | OOO-TG-CPZCQ          | 13247      | OOO-TG-CPZCQ  | 1          | 1000       | 1000       | 1000       | 8100000000   | 8100000000 | 10000000   | 3                   | 4              | 3          | NULL         | -1          | NULL         | NULL       | 3            | NULL        | NULL        | NULL           | 999999       | 999999     | NULL       | NULL       | 1          | 6          | 9999999       | 20170913 |
| 8100092    | 2017-01-02 17:53:59 | 2017-01-02 17:53:59 | OOO-TG-IUEU   | OMS-CPN-WH2 | OMS-CPN-WH2 | 5045              | OOO-TG-ZCQ            | 13248      | OOO-TG-ZCQ    | 1          | 1000       | 1000       | 1000       | 8100000000   | 8100000000 | 10000000   | 3                   | 4              | 3          | NULL         | 1           | NULL         | NULL       | 3            | NULL        | NULL        | NULL           | 999999       | 999999     | NULL       | NULL       | 1          | 6          | 9999999       | 20170913 |
+------------+------------+--------------+--------------+----------------+----------------+-------------------+---------------------+------------+--------------+------------+------------+------------+------------+--------------+------------+------------+---------------------+----------------+------------+--------------+-------------+--------------+------------+--------------+-------------+-------------+----------------+--------------+------------+------------+------------+------------+------------+---------------+----+
```

**Comment by oyz** [comment]
The reason of this error was found out,  it's because of the null data in the table.  The latest code has fixed this.

**Comment by giaosudau** [comment]
Why don't include partition field value in the result?

**Comment by oyz** [comment]
In maxcompute ,to read a partitioned table must specify the partitionSpec.
but the result record read from a specific partition not include partition value.

for sqoop, maybe we should add an option to enable appending partition values to result record for convenience.

**Comment by giaosudau** [comment]
It should be added because we want to load all data but without partition columns, we need to add a step to add data into.
